MODEL:
  TYPE: spatial_mamba
  NAME: base
  DROP_PATH_RATE: 0.5
  SPATIALMAMBA:
    EMBED_DIM: 96
    DEPTHS: [ 2, 4, 21, 5]
    D_STATE: 1
    MLP_RATIO: 4.0
    DT_INIT: 'random'
    
  DDP: 'torch'

TRAIN:
  EPOCHS: 300
  WARMUP_EPOCHS: 20
  MESA: 2.0
