MODEL:
  TYPE: spatial_mamba
  NAME: tiny
  DROP_PATH_RATE: 0.2
  SPATIALMAMBA:
    EMBED_DIM: 64
    DEPTHS: [ 2, 4, 8, 4]
    D_STATE: 1
    MLP_RATIO: 4.0
    DT_INIT: 'random'
    
  DDP: 'torch'

TRAIN:
  EPOCHS: 300
  WARMUP_EPOCHS: 20
  MESA: 1.0
